# serverless.yml
# NOTEs: (kard) 
# https://www.serverless.com/blog/serverless-express-rest-api
# https://stackoverflow.com/a/48254917
#
# To deploy use: 
# $ sls deploy
# 
# Tagging
# git tag -a step01 -m "Simple lambda within express server"
# git tag -n
# dit tag -d step01
# https://devconnected.com/how-to-create-git-tags/

# API endpoint
# https://rbpo5tghf1.execute-api.eu-central-1.amazonaws.com/dev

service: my-express-application

provider:
  name: aws
  lambdaHashingVersion: 20201221 # fix deprication warning
  runtime: nodejs12.x
  stage: dev
  region: eu-central-1
  profile: alt

functions:
  app:
    handler: app.handler
    events:
      - http: ANY /
      - http: 'ANY /{proxy+}'

