service: my-express-application

provider:
  name: aws
  lambdaHashingVersion: 20201221 # fix deprication warning
  runtime: nodejs12.x
  stage: dev
  region: eu-central-1
  profile: alt

functions:
  app:
    handler: app.handler
    events:
      - http: ANY /
      - http: 'ANY /{proxy+}'

